on:
  push:
    tags:
      - v*

permissions:
  contents: write
  packages: write

jobs:
  releases-matrix:
    name: Release KubeVirt Console
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: darwin
          - goarch: amd64
            goos: linux
          - goarch: arm64
            goos: linux
          - goarch: amd64
            goos: windows
    steps:
      - name: Show environment
        run: export
      - uses: actions/checkout@v4
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: wangyoucao577/go-release-action@v1
        # https://github.com/wangyoucao577/go-release-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_command: "make build"
          binary_name: "kubevirt-console"
          extra_files: kubevirt-console
          compress_assets: "OFF"
